### PR TITLE
Add mulit-label support

### PR DESCRIPTION
**Pull request by PepijnBoers**
Extends the Spacy classy skeleton to support multi-label classification, using a multi-layer perceptron.

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
@PepijnBoers didn't you finish yet? Or was closing it a mistake?

**Comment by PepijnBoers** [comment]
@davidberenstein1957 I was creating the feature for personal use and accidentally created the PR on your repo istd of my fork. But if you'd be interested in supporting multi-label classification in the main repo, I could make an actual PR. Let me know!

**Comment by PepijnBoers** [comment]
Ok, I'll probably work on it this week.

**Comment by PepijnBoers** [comment]
@davidberenstein1957 ready for review.

**Comment by PepijnBoers** [comment]
> @davidberenstein1957 ready for review.

What is the status on this?

**Comment by davidberenstein1957** [comment]
Hey Pepijn,

Sorry. I haven't really worked on my packages that much due to some busy
months. I'll work on it during the coming weeks.

Regards,
David

**Comment by davidberenstein1957** [comment]
Awesome! please take a look at my formatting preferences.

**Comment by miroslavtushev** [comment]
Hey, any updates on this? When is this going to be integrated?

**Comment by davidberenstein1957** [comment]
@PepijnBoers I took a while from my side, but thanks a lot for your contribution! I will fine-tune this today and add it to the next release.

**Comment by davidberenstein1957** [comment]
@PepijnBoers you can take a look at my initial refactoring. I expect to be able to wrap up the entire release coming Friday.

**Comment by davidberenstein1957** [comment]
@miroslavtushev See the comment above.

**Pull request merged**
